name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install xcresultparser
        run: |
          brew tap a7ex/homebrew-formulae
          brew install xcresultparser
          
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Build and Test
        env:
          platform: ${{ 'iOS Simulator' }}
        run: |
          mkdir -p artifacts
          xcodebuild test -project Memorize.xcodeproj -scheme Memorize -destination "platform=$platform,name=iPhone 16" -enableCodeCoverage YES -resultBundlePath artifacts/ResultBundle.xcresult

      - name: Convert xcresult to cobertura
        run: |
          xcresultparser --output-format cobertura "artifacts/ResultBundle.xcresult" > "artifacts/coverage.xml"
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: xmcnulty/Memorize-iOS
          disable_search: true
          files: artifacts/coverage.xml
          verbose: true
